# Generated by Django 2.1.1 on 2018-10-10 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutoManufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, unique=True, verbose_name='汽车厂商名')),
            ],
            options={
                'verbose_name': '厂商',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('automanufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nfsol.AutoManufacturer', verbose_name='厂商名')),
                ('name', models.CharField(default='', max_length=100, unique=True, verbose_name='品牌名')),
            ],
            options={
                'verbose_name': '品牌',
            },
        ),
        migrations.CreateModel(
            name='Carport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nfsol.Brand', verbose_name='品牌')),
                ('name', models.CharField(default='', max_length=100, unique=True, verbose_name='车名')),
                ('engine', models.IntegerField(default=0, verbose_name='引擎')),
                ('transmission', models.IntegerField(default=0, verbose_name='变速器')),
                ('nitrogen', models.IntegerField(default=0, verbose_name='氮气')),
                ('bumper', models.IntegerField(default=0, verbose_name='保险杠')),
                ('carriage', models.IntegerField(default=0, verbose_name='车架')),
                ('worth', models.BigIntegerField(default=0, verbose_name='价值')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '车库',
            },
        ),
        migrations.CreateModel(
            name='Parts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.SmallIntegerField(verbose_name='配件等级')),
                ('performance', models.SmallIntegerField(verbose_name='性能值')),
                ('upgrade', models.SmallIntegerField(verbose_name='升级配件数')),
                ('disassembly', models.SmallIntegerField(verbose_name='拆卸器数量')),
            ],
            options={
                'verbose_name': '配件',
            },
        ),
    ]
