# Generated by Django 2.1.1 on 2018-10-11 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lottery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('saletime', models.CharField(max_length=9, verbose_name='开售时间')),
                ('open_frequency', models.CharField(max_length=50, verbose_name='开奖频率')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='代码')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '彩种',
                'db_table': 'lottery',
            },
        ),
        migrations.CreateModel(
            name='LotteryNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lottery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lottery.Lottery')),
                ('periods', models.CharField(max_length=13, unique=True, verbose_name='期数')),
                ('opentime', models.DateTimeField(verbose_name='开奖时间')),
                ('number', models.CharField(max_length=100, verbose_name='开奖号码')),
                ('fluctuating', models.CharField(max_length=30, verbose_name='波动值')),
                ('tencent_online_number', models.IntegerField(verbose_name='腾讯在线人数')),
                ('ordernumber', models.IntegerField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '开奖号',
                'db_table': 'lottery_number',
            },
        ),
    ]
